### PR TITLE
refactoring and performance optimizations

### PR DESCRIPTION
**Pull request by okornev**

### CODE REVIEW

**Comment by bannama** [comment]
Changes in general look good, a few things to consider
1. any reason to have ESMessageProcessor extend DLQMessageProcessor?
2. we might need to keep the percolator mapping
3. while fetching the releases in DeploymentPlanProcessor, we may still have some old releases in cms-all index, so for backward compatibility we can look for releases in all cms* indices

**Comment by lkhusid** [comment]
@okornev,   I will merge this PR as is (subject to additional further QA testing).   Please discuss with @bannama his suggestions and if you decide to go for it, we will address with a follow-up PR.

**Comment by okornev** [comment]
I did the fixes https://github.com/oneops/search/pull/20

**Comment by okornev** [comment]
@lkhusid  https://github.com/oneops/search/pull/20

**Comment by okornev** [comment]
@bannama I did all 3 changes. But can you tell me why we need to keep percolator mapping? I thought it old Offerings specific (cost etc...) so we don't really need it?

**Pull request merged**
